version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/hashicorp/terraform
    versions:
    - 0.14.5
    - 0.14.6
    - 0.14.7
  - dependency-name: github.com/go-openapi/errors
    versions:
    - 0.19.9
  - dependency-name: github.com/go-openapi/swag
    versions:
    - 0.19.13
